### ISSUE TITLE
Centering image overflow, creating empty images

### ISSUE THREAD

**Issue by kristlv1** [CosmoAI-AES/CosmoSim#117] opened 2023-04-19 09:19 UTC
With certain parameters, the centering of images runs into an overflow error. See image below for parameters that causes a reproducible result (will create proper image without centering, and empty image with centering).

![image](https://user-images.githubusercontent.com/80821970/233028966-cc56476a-b70f-4517-9287-7b2ea5f23e71.png)
 
Arguments:
-X 50 -x 181.935 -E 33 -s 40 -n 50 -y 38.672 -M -C

Removing the -C argument (with or without -M) causes the problem.

**Comment by hgeorgsch** [comment] 2023-04-19 09:38
I am not able to reproduce this.  I think we use different versions; there may also be different versions of python, different versions of underlying libraries, or even differences between architectures.

However, I have created a new branch, speedup-centring, where I have tried to solve all the issues mentioned with centring.  Speedup depends on matrix operations replacing list operations.  The overflow may or may not be resolved by converting to floating point before calculations.  Could you test this @kristlv1 , please?  And tell me how it goes?

**Closed** 2023-04-19 10:42 UTC
Labels: bug
